language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm run test:cov
after_script: "npm install coveralls && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"
